In [109]:
import pandas as pd
import numpy as np

In [110]:
df = pd.read_csv('../data/dirty_cafe_sales.csv')

In [111]:
df.sample(15)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9382,TXN_4255580,ERROR,1,NaN,3.0,Cash,NaN,NaN
7083,TXN_1883231,Juice,5,3.0,15.0,ERROR,In-store,2023-10-21
5332,TXN_7414587,Tea,3,1.5,4.5,Cash,Takeaway,2023-03-22
5048,TXN_8324315,Salad,1,5.0,5.0,NaN,NaN,2023-08-07
1295,TXN_9143440,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-31
4795,TXN_1826919,Juice,4,3.0,12.0,Credit Card,In-store,2023-02-21
5694,TXN_3129441,Juice,3,3.0,9.0,Credit Card,In-store,2023-05-31
6036,TXN_4246000,Cookie,2,1.0,2.0,Credit Card,Takeaway,2023-07-09
6098,TXN_6568254,Salad,2,5.0,10.0,Credit Card,In-store,2023-02-09
981,TXN_4491072,Smoothie,4,4.0,16.0,Credit Card,NaN,2023-12-03
394,TXN_8224079,Cookie,5,1.0,5.0,Cash,In-store,2023-10-16
8063,TXN_2716940,Coffee,1,2.0,2.0,NaN,NaN,2023-11-27
8462,TXN_5398134,Coffee,2,2.0,4.0,Credit Card,UNKNOWN,2023-10-01
7096,TXN_6959065,Coffee,5,2.0,10.0,Digital Wallet,Takeaway,2023-05-05
8936,TXN_6053617,Sandwich,2,4.0,8.0,Credit Card,NaN,2023-11-25

## Obervações
- Nomes das colunas não estão em snake_case
- Campos em quantidade como 'UNKNOWN'
- Campos em 'price per unit como 'UNKNOWN'
- Alguns campos em 'Location' estão como Nan e outros como ERROR
- Todas as colunas são do tipo 'object'

In [112]:
print(df.info())
print(df.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB
None
Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

## Normalizando as colunas

In [113]:
df.columns = df.columns.str.lower().str.replace(" ","_")
df

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

# Substituindo valores faltantes por NaN
- O dataset usa valores como 'ERROR' para se referir a valores que estão faltando. Isso não permite que possamos fazer cálculos futuros na coluna em questão, diferente de 'NaN', onde o podemos tratá-lo de maneira nativa

In [114]:
 
valores_invalidos = ['ERROR','UNKNOWN','nan', '']

df = df.replace(valores_invalidos,np.nan)
df.sample(10)

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
4356,TXN_6617283,Tea,4,1.5,6.0,Digital Wallet,NaN,2023-06-09
7219,TXN_4152460,Sandwich,NaN,4.0,12.0,Cash,Takeaway,2023-05-01
143,TXN_8495063,Juice,1,3.0,NaN,Cash,NaN,2023-05-31
9279,TXN_6775304,Tea,4,1.5,6.0,Cash,In-store,2023-03-08
4749,TXN_5783469,Salad,NaN,5.0,15.0,NaN,NaN,2023-06-14
347,TXN_7140471,Cake,1,3.0,3.0,Credit Card,NaN,2023-05-25
2587,TXN_2614271,NaN,2,4.0,8.0,Digital Wallet,NaN,2023-08-03
2848,TXN_8619762,Smoothie,4,4.0,16.0,Cash,Takeaway,2023-08-05
5516,TXN_9720012,Smoothie,5,4.0,20.0,Cash,In-store,2023-09-25
4976,TXN_7780786,Cake,1,3.0,3.0,Credit Card,NaN,2023-10-30

## Transformando os tipos das colunas
- Como foi percebido na etapda de análise, todas as colunas estão como tipo 'object'. Temos que transformá-las nos tipos apropriados

In [115]:
#Transformando colunas para float
df['price_per_unit'] = pd.to_numeric(df['price_per_unit'], errors='coerce')
df['total_spent'] = pd.to_numeric(df['total_spent'], errors='coerce')

# Transformação para número inteiro
df['quantity'] = pd.to_numeric(df['quantity'],errors ='coerce').astype('Int64')

# Transformação para data
df['transaction_date'] = pd.to_datetime(df['transaction_date'],errors ='coerce')

print(df.dtypes)
df.sample(10)

transaction_id              object
item                        object
quantity                     Int64
price_per_unit             float64
total_spent                float64
payment_method              object
location                    object
transaction_date    datetime64[ns]
dtype: object

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
3339,TXN_2793054,Smoothie,4,4.0,16.0,NaN,Takeaway,2023-04-29
627,TXN_2681833,NaN,3,1.0,3.0,Digital Wallet,In-store,2023-10-05
8059,TXN_3655950,Cookie,1,1.0,1.0,NaN,In-store,2023-11-25
1292,TXN_4310310,Cake,3,3.0,9.0,Cash,Takeaway,2023-03-08
9307,TXN_2866587,Sandwich,3,4.0,12.0,Credit Card,NaN,2023-09-16
5079,TXN_8116676,Cake,2,3.0,6.0,Digital Wallet,NaN,2023-09-16
6617,TXN_1234390,Cake,2,3.0,6.0,Digital Wallet,Takeaway,2023-06-02
2260,TXN_9864212,Smoothie,5,4.0,20.0,NaN,NaN,NaT
9957,TXN_6487003,Coffee,<NA>,2.0,8.0,Credit Card,Takeaway,2023-11-15
6682,TXN_6815741,Smoothie,2,NaN,8.0,NaN,NaN,2023-03-13

# Imputação Lógica
- Alguns campos estão faltantes, mas podem ser preenchidos, pois temos informações suficientes para realizar essa tarefe
- Tome como exemplo o item 'Cake', onde, em certos momentos, temos o seu preço (3.0), mas em outros casos não temos. Como o preço do café não é desconhecido, podemos resolver esse problema de dados faltantes

In [170]:
precos = {
    'Coffee': 2.0, 'Tea': 1.5, 'Juice': 3.0, 'Smoothie': 4.0,
    'Sandwich': 4.0, 'Cake': 3.0, 'Cookie': 1.0, 'Salad': 5.0
}

df['price_per_unit'] = df['price_per_unit'].fillna(df['item'].map(precos))

df['total_spent'] = df['quantity'] * df['price_per_unit']
#df['quantity'] = df['total_spent'] / df['price_per_unit']
df.dropna(subset=['quantity','total_spent'],how='all',inplace=True)
df.dropna(subset=['item'],inplace=True)
df.sample(10)

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
8221,TXN_9567915,Cake,1,3.0,3.0,Digital Wallet,Takeaway,2023-06-30
6741,TXN_2556368,Smoothie,1,4.0,4.0,Digital Wallet,unknown,2023-10-26
6281,TXN_4147675,Tea,2,1.5,3.0,Credit Card,In-store,2023-01-04
1903,TXN_6236864,Tea,2,1.5,3.0,Digital Wallet,In-store,2023-08-17
5801,TXN_9262504,Smoothie,3,4.0,12.0,Credit Card,unknown,2023-12-01
4631,TXN_9024186,Juice,2,3.0,6.0,Cash,Takeaway,2023-12-17
6942,TXN_4064326,Cookie,2,1.0,2.0,Cash,Takeaway,2023-01-07
5882,TXN_5968705,Sandwich,3,4.0,12.0,Credit Card,Takeaway,2023-12-16
7144,TXN_3994585,Cake,3,3.0,9.0,Digital Wallet,In-store,2023-07-24

In [171]:
# Preechendo valores categóricos nulos
df['payment_method'] = df['payment_method'].fillna('unknown')
df['location'] = df['location'].fillna('unknown')
df.sample(10)

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
3024,TXN_6872268,Juice,2,3.0,6.0,Digital Wallet,In-store,2023-01-07
6948,TXN_3413156,Juice,1,3.0,3.0,Credit Card,In-store,2023-10-16
1802,TXN_9490163,Salad,4,5.0,20.0,Credit Card,unknown,2023-02-23
4563,TXN_7379007,Cake,2,3.0,6.0,unknown,Takeaway,NaT
2286,TXN_3425783,Juice,2,3.0,6.0,unknown,unknown,2023-06-15
373,TXN_8256593,Salad,2,5.0,10.0,Digital Wallet,Takeaway,2023-08-09
3928,TXN_7846513,Sandwich,3,4.0,12.0,Credit Card,unknown,2023-10-19
1081,TXN_5583534,Cookie,2,1.0,2.0,Cash,Takeaway,2023-10-31
4589,TXN_4475094,Sandwich,3,4.0,12.0,unknown,unknown,2023-08-12
1624,TXN_6708156,Tea,5,1.5,7.5,Credit Card,unknown,2023-11-26

## Checagem final

In [ ]:
duplicatas = df.duplicated(subset=['transaction_id']).sum()
duplicatas
if duplicatas > 0:
    df.drop_duplicates(subset=['transaction_id'],keep='first',inplace=True)

np.int64(0)